### PR TITLE
added documentation to my Map_Maker

### PR DESCRIPTION
**Pull request by emma4033**
My finished Map_Maker :))

### CODE REVIEW

**Review by ltatnell — APPROVED** [review]
very good

**Comment by ltatnell** [comment]
Very good very succinct, could maybe add some detail about the parameters?

**Review by anastasia-morf — COMMENTED** [review]
yay! looks great. maybe also add that it works with the MapMaker module?

**Comment by emma4033** [comment]
thank you for the comments @ltatnell and @anastasia-morf, I have changed up Map_maker and made a new pull request :))

**Pull request merged**
